Repository kubernetes/examples, pull requests merged in 2018-06, with the labels that each got.

#239 SECURITY_CONTACTS added
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/S

#242 Typo fix: Endpont->Endpoint
  staging/storage/rethinkdb/image/run.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#243 Add Azure Disk-based NFS volume option
  staging/volumes/nfs/README.md
  staging/volumes/nfs/provisioner/nfs-server-azure-pv.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/azure, size/M
