Repository kubernetes/examples, pull requests merged in 2018-04, with the labels that each got.

#212 Add details on mounting existing Azure Managed Disks
  staging/volumes/azure_disk/README.md
  staging/volumes/azure_disk/static-provisioning/managed-disk/pod-uses-existing-managed-disk.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#219 Update selenium examples to use deployments and newer selenium
  staging/selenium/README.md
  staging/selenium/selenium-hub-deployment.yaml
  staging/selenium/selenium-node-chrome-deployment.yaml
  staging/selenium/selenium-node-firefox-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#205 Add preempt verb for scheduler
  scheduler/scheduler-policy-config-with-extender.json
Labels: approved, cncf-cla: yes, lgtm, sig/scheduling, size/M

#224 Provide a more ideal example for scheduler extender policy.
  scheduler/scheduler-policy-config-with-extender.json
  staging/scheduler-policy-config-with-extender.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#201 Use docker to build cassandra jar file
  cassandra/Makefile
  cassandra/cassandra-statefulset.yaml
  cassandra/go/main.go
  cassandra/image/files/build.sh
  cassandra/image/files/cassandra-seed.h
  cassandra/image/files/kubernetes-cassandra.jar
  cassandra/java/pom.xml
  cassandra/java/src/main/java/io/k8s/cassandra/GoInterface.java
  cassandra/java/src/main/java/io/k8s/cassandra/KubernetesSeedProvider.java
  cassandra/java/src/test/java/io/k8s/cassandra/KubernetesSeedProviderTest.java
Labels: approved, cncf-cla: yes, lgtm, size/XL

#222 Add a sample for using azureFile for PVs
  staging/volumes/azure_file/README.md
  staging/volumes/azure_file/azure-2.yaml
  staging/volumes/azure_file/azure-pv.yaml
  staging/volumes/azure_file/azure-pvc.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/azure, size/M

#228 Add `snapfactor` readme for glusterfs provisioner examples.
  staging/persistent-volume-provisioning/README.md
  staging/persistent-volume-provisioning/glusterfs/glusterfs-storageclass.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS
