Repository kubernetes/examples, pull requests merged in 2018-05, with the labels that each got.

#229 Update New Relic Infrastructure Readme
  staging/newrelic-infrastructure/README.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#227 Fix cloud-dns README links
  staging/cluster-dns/README.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#232 Creation of PSP by hack/local-up-cluster.sh is not as automatic as the README suggests.
  staging/podsecuritypolicy/rbac/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S
