Repository kubernetes/examples, pull requests merged in 2018-03, with the labels that each got.

#207 elasticsearch prod: Add Role and RoleBinding for RBAC
  staging/elasticsearch/production_cluster/README.md
Labels: cncf-cla: yes, lgtm, size/XS

#211 [guestbook-go] Use multi-stage build
  guestbook-go/Dockerfile
  guestbook-go/Makefile
Labels: cncf-cla: yes, lgtm, size/S

#217 https-nginx: Correct tls.[crt|key] mount
  staging/https-nginx/default.conf
Labels: cncf-cla: yes, lgtm, size/XS

#208 podsecuritypolicy/rbac/README.md: update to use PSP from policy API group
  staging/podsecuritypolicy/rbac/README.md
Labels: cncf-cla: yes, do-not-merge/hold, size/XS

#215 Fix NFS tutorial README links
  staging/volumes/nfs/README.md
Labels: cncf-cla: yes, lgtm, size/M

#221 fix typo
  staging/mysql-cinder-pd/README.md
Labels: cncf-cla: yes, lgtm, size/XS
