Repository kubernetes/examples, pull requests merged in 2018-02, with the labels that each got.

#193 update all Deployment API version to apps/v1 in k8s v1.9.0 and add ac…
  cassandra/cassandra-statefulset.yaml
  guestbook/all-in-one/frontend.yaml
  guestbook/all-in-one/guestbook-all-in-one.yaml
  guestbook/all-in-one/redis-slave.yaml
  guestbook/frontend-deployment.yaml
  guestbook/redis-master-deployment.yaml
  guestbook/redis-slave-deployment.yaml
  mysql-wordpress-pd/mysql-deployment.yaml
  mysql-wordpress-pd/wordpress-deployment.yaml
  staging/cockroachdb/cockroachdb-statefulset.yaml
  staging/newrelic/README.md
  staging/newrelic/newrelic-daemonset.yaml
  staging/openshift-origin/etcd-controller.yaml
  staging/openshift-origin/etcd-discovery-controller.yaml
  staging/openshift-origin/openshift-controller.yaml
  staging/storage/hazelcast/README.md
  staging/storage/hazelcast/hazelcast-deployment.yaml
  staging/storage/minio/README.md
  staging/storage/minio/minio-distributed-statefulset.yaml
  staging/storage/minio/minio-standalone-deployment.yaml
  staging/sysdig-cloud/sysdig-daemonset.yaml
  staging/volumes/vsphere/README.md
  staging/volumes/vsphere/deployment.yaml
  staging/volumes/vsphere/simple-statefulset.yaml
Labels: cncf-cla: yes, lgtm, size/M

#195 add missing comment
  mysql-wordpress-pd/mysql-deployment.yaml
Labels: cncf-cla: yes, lgtm, size/XS

#196 Update README with new supported SC parameters.
  staging/persistent-volume-provisioning/README.md
Labels: cncf-cla: yes, lgtm, size/XS

#143 Provide xsd configuration for pom files
  cassandra/java/pom.xml
Labels: cncf-cla: yes, lgtm, size/XS

#198 cassandra: Replace deprecated ubuntu-slim image with debian-base from k8s
  cassandra/image/Dockerfile
  cassandra/image/Makefile
  cassandra/image/files/build.sh
Labels: cncf-cla: yes, lgtm, size/L

#142 Remove unused Java import package
  cassandra/java/src/main/java/io/k8s/cassandra/KubernetesSeedProvider.java
  cassandra/java/src/test/java/io/k8s/cassandra/KubernetesSeedProviderTest.java
Labels: cncf-cla: yes, size/XS

#199 Improve cassandra deployment
  cassandra/cassandra-statefulset.yaml
Labels: cncf-cla: yes, lgtm, size/S

#202 Add owners file to cassandra example
  cassandra/OWNERS
Labels: cncf-cla: yes, lgtm, size/XS

#203 Update owners for k/examples
  OWNERS
Labels: cncf-cla: yes, lgtm, size/S

#88 rbd: default image format to v2 instead of deprecated v1
  staging/persistent-volume-provisioning/README.md
Labels: cncf-cla: yes, lgtm, sig/storage, size/XS

#206 staging/podsecuritypolicy/rbac: use PSP from policy API group
  staging/podsecuritypolicy/rbac/policies.yaml
  staging/podsecuritypolicy/rbac/roles.yaml
Labels: cncf-cla: yes, lgtm, size/XS
