Repository kubernetes/examples, pull requests merged in 2019-01, with the labels that each got.

#290 Updated selenium hub health probes to recommended endpoints
  staging/selenium/selenium-hub-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#294 update redis image address
  staging/storage/redis/redis-master.yaml
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#296 Update OWNERS files to include link to docs
  OWNERS
  cassandra/OWNERS
  mysql-wordpress-pd/OWNERS
  staging/cockroachdb/OWNERS
  staging/cpu-manager/OWNERS
  staging/podsecuritypolicy/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/S

#284 Bump image versions in selenium example
  staging/selenium/selenium-hub-deployment.yaml
  staging/selenium/selenium-node-chrome-deployment.yaml
  staging/selenium/selenium-node-firefox-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS
