Repository kubernetes/examples, pull requests merged in 2019-05, with the labels that each got.

#304 Fix service dns name
  staging/cluster-dns/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#313 driver.close() should be driver.quit()
  staging/selenium/README.md
  staging/selenium/selenium-test.py
Labels: approved, cncf-cla: yes, lgtm, size/XS

#318 enable s390x to test containers
  guestbook/php-redis/Dockerfile
  guestbook/php-redis/Makefile
  guestbook/redis-slave/Makefile
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, size/S

#322 Update README.md
  staging/spark/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
