Repository kubernetes/examples, pull requests merged in 2023-02, with the labels that each got.

#470 Update Makefile to replace deprecated gcloud docker
  guestbook-go/Makefile
Labels: lgtm, cncf-cla: yes, size/XS, approved

#467 Updating README to reflect changes from #442
  staging/volumes/nfs/README.md
Labels: lgtm, cncf-cla: yes, size/S, approved

#462 chore: move registry from k8s.gcr.io to registry.k8s.io
  guestbook-go/README.md
  guestbook/all-in-one/guestbook-all-in-one.yaml
  guestbook/legacy/redis-master-controller.yaml
  guestbook/redis-master-deployment.yaml
  staging/cluster-dns/dns-backend-rc.yaml
  staging/cluster-dns/dns-frontend-pod.yaml
  staging/explorer/README.md
  staging/explorer/pod.yaml
  staging/spark/spark-gluster/spark-master-controller.yaml
  staging/spark/spark-gluster/spark-worker-controller.yaml
  staging/spark/spark-master-controller.yaml
  staging/spark/spark-worker-controller.yaml
  staging/spark/zeppelin-controller.yaml
  staging/storage/redis/redis-controller.yaml
  staging/storage/redis/redis-master.yaml
  staging/storage/redis/redis-sentinel-controller.yaml
  staging/storage/rethinkdb/admin-pod.yaml
  staging/storage/rethinkdb/rc.yaml
  staging/volumes/nfs/nfs-server-deployment.yaml
  staging/volumes/portworx/README.md
  staging/volumes/portworx/portworx-volume-pod.yaml
  staging/volumes/portworx/portworx-volume-pvcpod.yaml
  staging/volumes/portworx/portworx-volume-pvcscpod.yaml
  staging/volumes/scaleio/README.md
  staging/volumes/scaleio/pod-sc-pvc.yaml
  staging/volumes/scaleio/pod.yaml
  staging/volumes/vsphere/README.md
  staging/volumes/vsphere/simple-statefulset.yaml
  staging/volumes/vsphere/vsphere-volume-pod.yaml
  staging/volumes/vsphere/vsphere-volume-pvcpod.yaml
  staging/volumes/vsphere/vsphere-volume-pvcscpod.yaml
  staging/volumes/vsphere/vsphere-volume-pvcscvsanpod.yaml
Labels: lgtm, cncf-cla: yes, size/M, approved
