Repository kubernetes/examples, pull requests merged in 2025-05, with the labels that each got.

#556 Enable liveness checks for Cassandra
  cassandra/cassandra-statefulset.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, tide/merge-method-squash

#559 Revamp the example repo for modern use cases
  README.md
  ai/README.md
  guidelines.md
Labels: lgtm, cncf-cla: yes, size/L, approved

#560 Add SIG Apps leads to security contacts
  SECURITY_CONTACTS
Labels: lgtm, cncf-cla: yes, size/XS, approved

#561 Clean up broken analytics links
  cassandra/java/README.md
  guestbook-go/README.md
  guidelines.md
  mysql-cinder-pd/README.md
  staging/cluster-dns/README.md
  staging/cockroachdb/README.md
  staging/elasticsearch/README.md
  staging/elasticsearch/production_cluster/README.md
  staging/explorer/README.md
  staging/https-nginx/README.md
  staging/javaee/README.md
  staging/javaweb-tomcat-sidecar/README.md
  staging/job/expansions/README.md
  staging/job/work-queue-1/README.md
  staging/job/work-queue-2/README.md
  staging/meteor/README.md
  staging/meteor/dockerbase/README.md
  staging/newrelic-infrastructure/README.md
  staging/newrelic/README.md
  staging/nodesjs-mongodb/README.md
  staging/openshift-origin/README.md
  staging/persistent-volume-provisioning/README.md
  staging/phabricator/README.md
  staging/podsecuritypolicy/rbac/README.md
  staging/runtime-constraints/README.md
  staging/selenium/README.md
  staging/sharing-clusters/README.md
  staging/simple-nginx.md
  staging/spark/README.md
  staging/spark/spark-gluster/README.md
  staging/storage/hazelcast/README.md
  staging/storage/mysql-galera/README.md
  staging/storage/redis/README.md
  staging/storage/rethinkdb/README.md
  staging/storage/vitess/README.md
  staging/storm/README.md
  staging/sysdig-cloud/README.md
  staging/volumes/aws_ebs/README.md
  staging/volumes/azure_disk/README.md
  staging/volumes/azure_file/README.md
  staging/volumes/cinder/README.md
  staging/volumes/fibre_channel/README.md
  staging/volumes/flocker/README.md
  staging/volumes/nfs/README.md
  staging/volumes/nfs/nfs-data/README.md
  staging/volumes/portworx/README.md
  staging/volumes/quobyte/Readme.md
  staging/volumes/scaleio/README.md
  staging/volumes/vsphere/README.md
  volumes/cephfs/README.md
  volumes/glusterfs/README.md
  volumes/iscsi/README.md
  volumes/rbd/README.md
  volumes/storageos/README.md
Labels: lgtm, cncf-cla: yes, size/L, approved
